period1 = 50
period2 = 200

HZS = [
"Temperature",
"pH",
#"CO2",
"Dissolved oxygen (mg/l)",
#"Dissolved oxygen [%]",
#"Conductivity",
"Conductivity at 25°C",
#"Salinity",
#"Resistivity",
"ORP Redox potential",
#"Seawater Specific Gravity",
"Chloride (mg/l)",
#"Nitrate",
#"Sulphur ions",
#"Biofilm",
"Chlorophyll [µg/l]",
#"Turbidity",
#"TDS (Total Dissolved Solids)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
"Metal loss in um"
]

UGent = [
"Temperature",
"pH",
#"CO2",
"Dissolved oxygen (mg/l)",
#"Dissolved oxygen [%]",
#"Conductivity",
"Conductivity at 25°C",
#"Salinity",
#"Resistivity",
"ORP Redox potential",
#"Seawater Specific Gravity",
#"Chloride (mg/l)",
#"Nitrate",
#"Sulphur ions",
#"Biofilm",
#"Chlorophyll [µg/l]",
#"Turbidity",
#"TDS (Total Dissolved Solids)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal loss in um"
]

OCAS = [
"Temperature",
"pH",
#"CO2",
"Dissolved oxygen (mg/l)",
#"Dissolved oxygen [%]",
#"Conductivity",
"Conductivity at 25°C",
#"Salinity",
#"Resistivity",
"ORP Redox potential",
#"Seawater Specific Gravity",
"Chloride (mg/l)",
#"Nitrate",
#"Sulphur ions",
#"Biofilm",
#"Chlorophyll [µg/l]",
#"Turbidity",
#"TDS (Total Dissolved Solids)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal loss in um"
]

KUL = [
"Temperature",
"pH",
#"CO2",
"Dissolved oxygen (mg/l)",
#"Dissolved oxygen [%]",
#"Conductivity",
"Conductivity at 25°C",
#"Salinity",
#"Resistivity",
"ORP Redox potential",
#"Seawater Specific Gravity",
#"Chloride (mg/l)",
#"Nitrate",
#"Sulphur ions",
#"Biofilm",
#"Chlorophyll [µg/l]",
"Turbidity",
#"TDS (Total Dissolved Solids)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
"Corrosion rate (LPR)",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Pitting indication LPR",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal Loss in A (ER)",
#"Metal loss in um"
]

#  Model 1: HZS     Model 2: KUL  and  Model 3: UGent
models = {'model1': HZS, 'model2': KUL, 'model3': UGent }
